### ISSUE TITLE
Refactor privileged accounts

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/cyberway#128]
Privileged accounts can be used for 'god' mode

**Comment by zxcat** [comment]
- [x] 1. Remove `set_privileged` intrinsic and system `setpriv` action. Privileged flag can be set only on account create or with hardfork.
- [ ] 2. Prepare list of system contracts and disable changing code and abi of system contracts without hardfork
- [x] 3. Create privileged `msig` contract at genesis block
    - [ ] fix `cyberway.contracts` tests
- [ ] 4. ?Remove `wrap` contract?

**Comment by zxcat** [comment]
PR #293
