### ISSUE TITLE
Optimize iterators for lazy load

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/cyberway#152]
There are several cases when chaindb controller shouldn't call the driver to create cursor:
- begin() - returns iterator
- end() - returns iterator
- emplace() - returns iterator

All these cases can be optimized by lazy create of cursor in DB, because iterator has enough information for it.

In case of emplace() - iterator should be initialized with (`pk`, `cache_item`), and call chaindb-controller only when operators '++' and '--' is called.
In case of begin() and end() - iterator should be initialized with special state, it is enough for comparison (which is real critical in case of end-iterator).

**Comment by e-schepachev** [comment]
PR #156
