### ISSUE TITLE
nodeos crash when access usernames table

### ISSUE THREAD

**Issue by zxcat** [GolosChain/cyberway#190]
**Steps to reproduce:** `cleos resolve name test@@eosio` — this tries to read username `test` from the scope of `eosio` account.

**Expected results:** "username not found" error message

**Actual results:** nodeos silent crash (try/catch fails to catch it)
***
**Additional info:**
`cleos resolve name` calls `resolve_names` api, which tries to get username info here:             https://github.com/GolosChain/cyberway/blob/bcb994cf3d0714fc1d9dec020f4457d0918c720a/plugins/chain_plugin/chain_plugin.cpp#L1809
`get_username` defined here: https://github.com/GolosChain/cyberway/blob/bcb994cf3d0714fc1d9dec020f4457d0918c720a/libraries/chain/controller.cpp#L2179-L2184
`username_object` and multi_index: https://github.com/GolosChain/cyberway/blob/bcb994cf3d0714fc1d9dec020f4457d0918c720a/libraries/chain/include/eosio/chain/domain_object.hpp#L41
table: https://github.com/GolosChain/cyberway/blob/bcb994cf3d0714fc1d9dec020f4457d0918c720a/libraries/chain/controller.cpp#L637

**Comment by afalaleev** [comment]
PR #199
