### ISSUE TITLE
Refactor chainbase to use external database

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/cyberway#2]
To give application flexible way to get information from blockchain state
we can export smart-contacts tables to external database.

Steps:
- Create simple implementation of multi-index
- Create context of multi-index for export structure of table to external database
- Implement read-write callbacks from multi-index to external database
- Implement find/upper_bound/lower_bound callbacks to external database

**Comment by kotbegemot** [comment]
Why is there so much code in the ansi-c style?
Why is not there a double level of abstractions from mongodb for chaindb?
Why, for example, does not use boost :: iterator_adaptor?
How good is use of boost.hana?

**Comment by afalaleev** [comment]
There is two parts: for smart contracts (and it is a bad idea to use boost iterator_adaptor for it), and c-style layer for integration with webassembler.
There is no full cover of all invariants, only for smart contracts level, which is enough for the prototype.

**Comment by kotbegemot** [comment]
Why do you think that you will not fall into the trap of the prototype?
I will open my mysle.
There is fear.
that the prototype worked and in the production there?
You did not answer the question about boost.hana. @afalaleev

**Comment by afalaleev** [comment]
boost::hana is a good realization for small projects like smart contacts.
For cases which are not covered by the realization, issues were created and they will be fixed later, and the current time we have other priority tasks.

Please, if you an adherent of boost libraries or want to ask some information about them - you can discuss them in their mailing list and other places for discussions.

**Comment by kotbegemot** [comment]
> Please, if you an adherent of boost libraries or want to ask some information about them - you can discuss them in their mailing list and other places for discussions.

Please do not translate the subject.
I'm trying to figure out your solution design.

Why chaindb is built not as a parametrizable component.
Why can not chaindb be parameterized in runtime?
Why does chaindb have a tough link to mongodb?

**Comment by afalaleev** [comment]
A runtime/compile selection will be implement in other issue.
Implementation in this issue doesn't have an integration with CyberWay.
