### ISSUE TITLE
Ошибка создания поста с постинг ключом

### ISSUE THREAD

**Issue by MachtFrei** [GolosChain/cyberway#318]
При попытке написать пост с постинг ключом выдает ошибку
INFO: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"Provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"tst2dqdoosrs\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\"GLS6j7RMv9XzPK7uhYCze42BhNHvt16Jbtyn4FFzU6tvJDTUrQ5Mg\"], and a delay max limit of 3888000000 ms","file":"authorization_manager.cpp","line_number":520,"method":"check_authorization"}]}}

**Comment by s-medvedev** [comment]
Это не ошибка cyberway.
Смарт-контракты при проверке прав доступа проверяют active-авторити. Если пользователь хочет вызывать метод с использованием другой авторити, он должен выполнить привязку этой авторити к методу. Делается это командой: `cleos set action permission <user> <contract> <action> <authority>`
