### ISSUE TITLE
Fix works with eosio::chain::allocator in internal chain tables

### ISSUE THREAD

**Issue by s-medvedev** [GolosChain/cyberway#44]
Now shared_multi_index_container2 saves some data using shared memory. So on start it's need to clear own state and it's make this with simply remove named structure from shared memory.
This method leaves a lot of garbage that will never be removed from shared memory. It is necessary to correct this implementation (don't use shared memory allocator or clear used memory more carefully)

**Comment by afalaleev** [comment]
Closed in #45
