### ISSUE TITLE
Enable executes gls.publish actions with posting authority for Golos accounts

### ISSUE THREAD

**Issue by s-medvedev** [GolosChain/cyberway#540]
Users should be able to post and vote using their posting key. 
To implement this, when loading the genesis, it's need to create an entry for each user allowing him to perform the actions of a posting smart-contract with a posting key.

Cleos command:
`cleos set action permission <user> gls.publish "" posting`

This command create linkauth record:
```
> db.permlink.find({id:5}).limit(1).pretty()
{
	"_id" : ObjectId("5cb9b427ec8a5453357c07b0"),
	"id" : NumberDecimal("5"),
	"account" : "..tomqqhsvwz",
	"code" : "gls.publish",
	"message_type" : "",
	"required_permission" : "posting",
	"_SERVICE_" : {
		"scope" : "",
		"rev" : NumberLong(1),
		"payer" : "..tomqqhsvwz",
		"size" : 327
	}
}
```

**Comment by zxcat** [comment]
PR #588
