### ISSUE TITLE
Restore `./eosio_build.sh` command 

### ISSUE THREAD

**Issue by boostmultifruit** [GolosChain/cyberway#682]
https://github.com/GolosChain/cyberway/commits/develop is not building after merging yesterday pull-request https://github.com/GolosChain/cyberway/pull/644

My quickfix only to return to life (problem line is here):
https://github.com/GolosChain/cyberway/pull/681/files#diff-fa869161a34daa6e6ef99479a3593214R42
Should be fixed correctly.

**Comment by afalaleev** [comment]
Resolved in PR #681
