### ISSUE TITLE
Cursor leak in smart contracts

### ISSUE THREAD

**Issue by e-schepachev** [GolosChain/cyberway#872]
If smart contract access to another smart contract storage it can cause to a cursor leak:
1) Smart contract gain an iterator and then web assembler vm interrupts because of timeout.
2) Smart contract accesses to a storage through chaindb_begin/end/.. intrinsic function
3) Intrinsic function can implicitly call chaindb_begin/end functions

In that cases a multi_index iterator destructor will not be called and will not remove cursor from the cursor map inside the node memory. The chaindb_guard with closes all cursor opened inside the apply_context also will skip cursors which parent 'code' differs from the  running smart contract 'code'.

**Comment by afalaleev** [comment]
Request to use the `chaindb_cursor_cache` to store opened cursors:
https://github.com/GolosChain/cyberway/blob/b5a1a3d1d630ffcd054b397ba63afa19dbb5188b/libraries/chain/apply_context.cpp#L71

In #854 you implements the `sync_find_info` - https://github.com/GolosChain/cyberway/blob/46c758dbc14c0566314169a95aed7443ff24c9cf/libraries/chain/include/cyberway/chaindb/controller.hpp#L27-L42

After moving logic of storing opened cursors to the `chaindb_cursor_cache`, there is no reasons to have two types of `sync_/find_info`. We should merge logic to one structure/
