### ISSUE TITLE
Add info about producer who generated block

### ISSUE THREAD

**Issue by s-medvedev** [GolosChain/cyberway#877]

**Comment by afalaleev** [comment]
**Fields to add from `block_header_state`**:
- active_schedule::producers _(only producer_name, w\o block_signing_key)_
- scheduled_shuffle_slot
- dpos_irreversible_blocknum

**Fields to add from `block_header`**:
- producer

**Calculated fields to add**:
- block_slot:
```
block_timestamp_type(block_header::timestamp).slot
```
- schedule_slot:
```
(block_slot - (block_header_state::scheduled_shuffle_slot + 1)) % block_header_state::active_schedule.producers.size()
```
- next_block_time:
```
block_header::timestamp + fc::microseconds(chain::config::block_interval_us);
```
- next_schedule:
```
auto next = block_header_state::generate_next(next_block_time);
next.update_active_schedule();
next_schedule = next.active_schedule::producers; // (only producer_name, w\o block_signing_key)
```
**Fields to remove**:
- validated
- in_current_chain
