### ISSUE TITLE
Create of EE genesis fails on delegate generation

### ISSUE THREAD

**Issue by afalaleev** [GolosChain/cyberway#905]
```
error 2019-07-03T16:10:01.732 create-ge main.cpp:221                  main                 ] 3015014 pack_exception: Pack data exception
Missing field 'from' in input object while processing struct 'delegate'
    {"f":"from","p":"delegate"}
    create-genesis  abi_serializer.cpp:544 _variant_to_binary

    {"type":"delegate","var":{"delegator":"i3s3fihrupb4","delegatee":"t3ohiuuc4ngf","quantity":"3609.794546 GOLOS","interest_rate":0,"min_delegation_time":"2018-06-20T09:04:06.000","id":0}}
    create-genesis  abi_serializer.cpp:571 _variant_to_binary

    {"type":"delegate","var":{"delegator":"i3s3fihrupb4","delegatee":"t3ohiuuc4ngf","quantity":"3609.794546 GOLOS","interest_rate":0,"min_delegation_time":"2018-06-20T09:04:06.000","id":0}}
    create-genesis  abi_serializer.cpp:585 _variant_to_binary
```

Description of delegation in ee-genesis:
https://github.com/GolosChain/cyberway/blob/411a48a0f19055a915c84e17064fced4682ac7eb/programs/create-genesis/ee_genesis/event_engine_genesis.cpp#L92-L107

It is different than delegation in genesis:
https://github.com/GolosChain/cyberway/blob/411a48a0f19055a915c84e17064fced4682ac7eb/programs/create-genesis/genesis_create.cpp#L808-L813

Exporting of delegation from genesis:
https://github.com/GolosChain/cyberway/blob/411a48a0f19055a915c84e17064fced4682ac7eb/programs/create-genesis/genesis_create.cpp#L816

And using it in ee-genesis:
https://github.com/GolosChain/cyberway/blob/411a48a0f19055a915c84e17064fced4682ac7eb/programs/create-genesis/ee_genesis/genesis_ee_builder.cpp#L563-L565

**Comment by boostmultifruit** [comment]
PR #906
