### ISSUE TITLE
Improve chaindb_controller to better handle next/prev

### ISSUE THREAD

**Issue by zxcat** [GolosChain/cyberway#96]
Some tests require to get all rows of some table. `golos_tester::get_all_chaindb_rows` implements this for chaindb, but now it uses workaround with magic number (uint -1) to check table end: https://github.com/GolosChain/golos-smart/blob/6151cbc24fe411025217be17eec1859ea3bf9395/tests/golos_tester.cpp#L174

The problem is that record can contain such primary key (-1), in this case method will return invalid result.

Propose update chaindb so `value_at_cursor` return `null` object when `next`/`prev` methods reach boundary. Or add some other marker that boundary reached.

Note: low priority

**Comment by maslenitsa93** [comment]
0xFFF... is a magic number but it can be replaced with constant `end_primary_key`.
Can I ask is it good that record can contain primary key which identifies end cursor? :)

**Comment by maslenitsa93** [comment]
I think I solved problem without updating `value_at_cursor`.
See this fix:
https://github.com/GolosChain/golos-smart/commit/53bd42f1b2914fc2d6c4fb3fc6524b34517a7373#diff-b68ff9134b7cf77901597d264658f8d0
Now I exiting loop if current primary_key is same as previous. AFAIK, primary keys are unique and such equation could occur only if next() reached end. But in this case we don't check it with specific magic number.
Note: commit looks ugly, but neccessary changes are only in `get_all_chaindb_rows`, all another changes are temporary for test purposes.

**Comment by afalaleev** [comment]
Closed by PR #182
